services:
  postgres:
    image: pgvector/pgvector:pg16
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "25432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 1s

volumes:
  postgres_data:
