[package]
name = "entity"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = { version = "1.16.0", features = ["zerocopy", "v7"] }
sea-orm = { version = "1.1.10", features = [
  "postgres-vector",
  "sqlx-postgres",
  "runtime-tokio-rustls",
  "with-uuid",
] }
